config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'

  resources :admin

  # get 'home', to: 'admin#index'
  resources :users
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/user/create', to: 'users#create'
  get '/user/edit', to: 'users#edit'
  get '/user/delete', to: 'users#destroy'


  resources :contacts, only: [:index, :show, :edit, :new]
  resources :companies, shallow: true do
    collection { post :import }

    resources :contacts
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  # get '/logout', to: 'sessions#detroy'

end

app/controllers/company_contacts_controller.rb
class CompanyContactsController < ApplicationController
  # before_action :authenticate, only: [:index, :show, :edit, :update, :destroy]


  def index
    @company_contacts = CompanyContact.all

    if params[:search]
      @company_contacts = CompanyContact.search(params[:search]).order("created_at DESC")
    else
      @company_contacts = CompanyContact.order("created_at DESC")
    end
  end

  def new
    @company_contact = CompanyContact.new
  end

  def edit
  @company_contact = CompanyContact.find(params[:id])
  end

  def create
    @company_contact = CompanyContact.new(company_contact_params)
    if @company_contact.save
      flash[:notice] = "The company has been created"
      redirect_to company_contacts_path
    else
      render 'new'
    end
  end

  def update
    @company_contact = CompanyContact.find(params[:id])

    if @company_contact.update(company_contact_params)
      flash[:notice] = "The company has been updated created"
      redirect_to company_contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @company_contact = CompanyContact.find(params[:id])
    @company_contact.destroy
    redirect_to company_contacts_path
  end

private
  def company_contact_params
    params.require(:company_contact).permit(:name,
                                    :email,
                                    :office_number,
                                    :cellphone_number,
                                    :job_title,
                                    :profile_pic_uri,
                                    :company_contact_id,
                                    :company_id)
  end


#     # def authenticate
#     #   redirect_to '/login', alert: "You must login to continue!" if @current_company.nil?
#     # end
end

app/views/company_contacts/_form.html.erb
<h2>Contacts page >> Create/Edit a contact</h2>

<%= form_for @company_contact do |f| %>
  <% if @company_contact.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @company_contact.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Id %>
    <%= f.text_field :company_contact_id %>
  </div>

  </div>
    <div class="field">
    <%= f.label :Picture %>
    <%= f.text_field :profile_pic_uri %>
  </div>
  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :Title %>
    <%= f.text_field :job_title %>
  </div>
    <div class="field">
    <%= f.label :Email %>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :Office_number %>
    <%= f.text_field :office_number %>
  </div>
    <div class="field">
    <%= f.label :Cellphone %>
    <%= f.text_field :cellphone_number %>
  </div>

  <div class="actions"><%= f.submit %>
  </div>

<% end %>

app/views/company_contacts/index.html.erb
<h2>Contacts main page</h2>

<h3><%= link_to 'New client', new_company_contact_path %></h3>
<h4>
    <!-- When submit the form, the view rendered will be the index view of our articles resource -->
  <%= form_tag(company_contacts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Type contact name" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i>Search</button>
      <%= submit_tag "Clear", :class => 'inputsubmit', :type => 'reset'%>

    </div>
  <% end %>
</h4>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Picture</th>
      <th>Name</th>
      <th>Job Title</th>
      <th>Email Type</th>
      <th>Office Num</th>
      <th>Cellphone</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_contacts.each do |company_contact| %>
      <tr>
        <td><%= company_contact.company_contact_id %></td>
        <td><%= company_contact.profile_pic_uri %></td>
        <td><%= company_contact.name %></td>
        <td><%= company_contact.job_title %></td>
        <td><%= company_contact.email %></td>
        <td><%= company_contact.office_number %></td>
        <td><%= company_contact.cellphone_number %></td>

        <td><%= link_to 'Edit', edit_company_contact_path(company_contact) %></td>
        <td>
          <%= button_to "Delete", { action: "destroy", :controller => :company_contacts, id: company_contact.id },
          method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>