config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'

  resources :admin

  # get 'home', to: 'admin#index'
  resources :users
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/user/create', to: 'users#create'
  get '/user/edit', to: 'users#edit'
  get '/user/delete', to: 'users#destroy'


  resources :contacts, only: [:index, :show, :edit, :new]
  resources :companies, shallow: true do
    collection { post :import }

    resources :contacts
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  # get '/logout', to: 'sessions#detroy'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :contacts, dependent: :destroy

  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end

  # def self.to_csv(options = {})
  #   CSV.generate(options) do |csv|
  #     csv << column_names
  #     all.each do |company|
  #       csv << company.attributes.values_at(*column_name)
  #     end
  #   end
  # end


  def self.search(query)
    where(
      "company_name LIKE ? OR company_type LIKE ? OR city LIKE ? OR country LIKE ? OR telephone LIKE ?",
      "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%"
    )
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # before_action :authenticate, only: [:index, :show, :edit, :update, :destroy]


  def index
    @companies = Company.all

    if params[:search]
      @companies = Company.search(params[:search]).order(created_at: :desc)
    else
      @companies = Company.order(created_at: :desc)
    end

    @companies = @companies.paginate(:page => params[:page], :per_page => 5)
  end


  def new
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = "The company has been created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      flash[:notice] = "The company has been updated created"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to '/'
  end

  def import
    @company = Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Successfully"
  end

#   def export
#     @company = Company.order(:name)
#     respond_to do |format|
#       format.html
#       format.csv { send_data @companies.to_csv }
#       format.xls #{ send_data @compnaies.to_csv(col_sep: "\t") }
#   end
# end

private
  def company_params
    params.require(:company).permit(:count,
                                    :logo,
                                    :company_name,
                                    :company_size,
                                    :company_type,
                                    :telephone,
                                    :logo_uri,
                                    :fax,
                                    :address,
                                    :city,
                                    :state,
                                    :country,
                                    :zip_code,
                                    :website_uri,
                                    :facebook_uri,
                                    :email,
                                    :linkedin_uri)
  end


    # def authenticate
    #   redirect_to '/login', alert: "You must login to continue!" if @current_company.nil?
    # end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="company_form">
<%= form_for @company do |f| %>
  <% if @company.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @company.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<table class="table table-hover table-striped">
  <thread>
          <tr><td class="info"><label>Create or Edit a company</label>
           </td></tr>

          <tr><td class="field" >
            <%= f.label :Count %></br>
            <%= f.text_field :count %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Name %></br>
            <%= f.text_field :company_name %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Size %></br>
            <%= f.text_field :company_size %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Type %></br>
            <%= f.text_field :company_type %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Logo %></br>
            <%= f.text_field :logo_uri %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Telephone %></br>
            <%= f.text_field :telephone %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Fax %></br>
            <%= f.text_field :fax %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Email %></br>
            <%= f.text_field :email %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Website %></br>
            <%= f.text_field :website_uri %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Facebook %></br>
            <%= f.text_field :facebook_uri %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :LinkedIn %></br>
            <%= f.text_field :linkedin_uri %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Address %></br>
            <%= f.text_field :address %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :City %></br>
            <%= f.text_field :city %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :State %></br>
            <%= f.text_field :state %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Zip %></br>
            <%= f.text_field :zip_code %>
          </td></tr>

          <tr><td class="field">
            <%= f.label :Country %></br>
            <%= f.text_field :country %>
          </td></tr>

          <tr><td class="actions"><%= f.submit %>
          </td></tr>
          <% end %>
    </thread>
</table>
<div class="form-group">

app/views/companies/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="companies">
<div class="navbar-text pull-left">
  <span class="btn">
    <%= link_to 'New Company', new_company_path %>
  </span>
</div>

<div class="navbar-text pull-right">
  <%= form_tag(companies_path, :method => "get", class: "navbar-form inline-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search" %>
      <button class="btn" type="submit"><i class="icon-search"></i>Search</button>
    </div>
  <% end %>
  <%= button_to "Clear", companies_path, method: :get, form_class: "inline-form", class: "btn" %>
</div>



<table class="table table-striped table-hover table-condensed table-responsive">
  <thead>
    <tr class="info">
      <th>Id</th>
      <th>Company Name</th>
      <th>Company Size</th>
      <th>Company Type</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Website</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Contact?</th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.count %></td>
        <td><%= company.company_name %></td>
        <td><%= company.company_size %></td>
        <td><%= company.company_type %></td>
        <td><%= company.telephone %></td>
        <td><%= company.email %></td>
        <td><%= company.website_uri %></td>
        <td><%= company.city %></td>
        <td><%= company.state %></td>
        <td><%= company.country %></td>
        <% if company.contacts.length > 0 %>
          <td><%= link_to "Contacts", company_contacts_path(company) %></td>
        <% else %>
          <td>No contacts</td>
        <% end %>
        <td><%= link_to 'Details', company_path(company) %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td>
          <%= button_to "Delete", { action: "destroy", :controller => :companies, id: company.id },
          method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="btn-group" role="group">
<h4>Upload file</h4>
  <%= form_tag import_companies_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<nav>
  <ul class="pagination">
    <li id="pages"><%= will_paginate @companies %></li>
  </ul>
</nav>
</div>

app/views/companies/index.xls.erb
<!-- <?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>

      </Row>
    <% @companies.each do |company| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= company.company_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.company_name %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook> -->

app/views/companies/new.html.erb
<h1>Create a new company</h1>
<%= form_for @company do |f| %>
  <% if @company.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @company.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Count %>
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :company_name %>
  </div>
    <div class="field">
    <%= f.label :Num_of_Employees %>
    <%= f.text_field :company_size %>
  </div>
  <div class="field">
    <%= f.label :Type %>
    <%= f.text_field :company_type %>
  </div>
    <div class="field">
    <%= f.label :Logo %>
    <%= f.text_field :logo_uri %>
  </div>
    <div class="field">
    <%= f.label :Telephone %>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :Website %>
    <%= f.text_field :website_uri %>
  </div>

  <div class="field">
    <%= f.label :Website %>
    <%= f.text_field :website_uri %>
  </div>

  <div class="field">
    <%= f.label :Facebook %>
    <%= f.text_field :facebook_uri %>
  </div>

  <div class="field">
    <%= f.label :LinkedIn %>
    <%= f.text_field :linkedin_uri %>
  </div>

  <div class="field">
    <%= f.label :Address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :City %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :State %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :Country %>
    <%= f.text_field :country %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/companies/show.html.erb
<div class="company_edit">

<table class="table table-hover table-striped table-condensed">
  <thread>
          <tr><td class="info"><label>Company details page</label>
           </td></tr>

            <tr><td>
              <strong><%= link_to "Add a contact", new_company_contact_path(@company) %></strong>
           </td></tr>

           <tr><td>
            <strong>Company id:</strong>
            <%= @company.count %>
          </td></tr>

          <tr><td>
            <strong>Logo:</strong>
            <%= @company.logo_uri %>
          </td></tr>

          <tr><td>
            <strong>Company Name:</strong>
            <%= @company.company_name %>
          </td></tr>

          <tr><td>
            <strong>Company Size:</strong>
            <%= @company.company_size %>
          </td></tr>

          <tr><td>
            <strong>Company Type:</strong>
            <%= @company.company_type %>
          </td></tr>

          <tr><td>
            <strong>Telephone:</strong>
            <%= @company.telephone %>
          </td></tr>

          <tr><td>
            <strong>Fax:</strong>
            <%= @company.fax %>
          </td></tr>

          <tr><td>
            <strong>Email:</strong>
            <%= @company.email %>
          </td></tr>

          <tr><td>
            <strong>Address:</strong>
            <%= @company.address %>
          </td></tr>

          <tr><td>
            <strong>City:</strong>
            <%= @company.city %>
          </td></tr>

          <tr><td>
            <strong>State:</strong>
            <%= @company.state %>
          </td></tr>

          <tr><td>
            <strong>Zip Code:</strong>
            <%= @company.zip_code %>
          </td></tr>

          <tr><td>
            <strong>Country:</strong>
            <%= @company.country %>
          </td></tr>

          <tr><td>
            <strong>Website:</strong>
            <%= @company.website_uri %>
          </td></tr>

          <tr><td>
            <strong>Facebook page:</strong>
            <%= @company.facebook_uri %>
          </td></tr>

          <tr><td>
            <strong>LinkedIn page:</strong>
            <%= @company.linkedin_uri %>
          </td></tr>
            <tr><td>
                <%= link_to 'Edit', edit_company_path(@company) %> |
                <%= link_to 'Back', companies_path %>
            </td></tr>
    </thread>
</table>
</div>