config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'

  resources :admin

  # get 'home', to: 'admin#index'
  resources :users
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/user/create', to: 'users#create'
  get '/user/edit', to: 'users#edit'
  get '/user/delete', to: 'users#destroy'


  resources :contacts, only: [:index, :show, :edit, :new]
  resources :companies, shallow: true do
    collection { post :import }

    resources :contacts
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  # get '/logout', to: 'sessions#detroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

</head>

<body>
</header>

  <div class="navbar navbar-default breadcrumb" id="top_nav_bar">
    <div class="navbar-header">
        <ul class="nav navbar-nav">
            <div class="nav navbar-nav" id="welcome">
               <% if current_user %>
                <li>Welcome, <%= current_user.name %>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
            </div>
                <a href="https://www.dropbox.com/s/p22vngs4vj7vaxa/readme.pdf?dl=0" class="navbar-btn btn-success btn pull-right">ReadMe</a>
                <a href="https://github.com/sebasa1984/CMS" class="navbar-btn btn-danger btn pull-right">GitHub</a>
                <a href="https://www.linkedin.com/in/sebsal" class="navbar-btn btn-primary btn pull-right">LinkedIn</a>
          <li><%= link_to 'Logout', session_path('dummy'), method: :delete %></li>

              <% else %>
             <li><%= link_to 'Login', login_path %></li>

          <!--     <%= link_to 'Sign Up', new_user_path %> -->
            <% end %>
             <li><%= link_to 'Companies', controller: 'companies' %></li>


            <li><%= link_to 'Contacts', contacts_path %></li>
            <!-- &nbsp;&nbsp;|&nbsp;&nbsp; -->

            <li><%= link_to 'Users', controller: 'users' %></li>
            <!-- &nbsp;&nbsp;|&nbsp;&nbsp; -->


        </ul>
      </div>
    </div>
  </div>


<%= yield %>

  </header>

  <div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-footer">
      <p class="navbar-text pull-left">Copyright © 2015, All rights reserved - Sebastian Salazar</p>


  </div>
</div>

</body>

</html>